#!/usr/bin/env python3
"""Build the visual catalogue of viewers and dashboards.

Writes two things:

* ``docs/viewers/index.md`` — every application, grouped as the portal groups
  them, with a thumbnail for each;
* a "Viewers in this section" gallery appended to each of the eight portal
  pages that a group belongs to.

The per-page galleries are written between marker comments, so re-running this
after a fresh scrape replaces them instead of stacking up copies.

Run this after ``scrape_to_md.py``; it reads the catalogue that
``capture_thumbnails.py`` produced.

Usage::

    python scripts/build_gallery.py
"""

from __future__ import annotations

import html
import json
import sys
from pathlib import Path

CATALOGUE = Path("docs/_data/applications.json")
THUMBS_DIR = Path("docs/_static/thumbnails")
VIEWERS_INDEX = Path("docs/viewers/index.md")
PAGES_DIR = Path("docs/pages")

START = "<!-- gallery:start - generated by scripts/build_gallery.py, do not edit -->"
END = "<!-- gallery:end -->"

# Each group in the portal's catalogue is described by one of its content
# pages; that page is where the group's gallery belongs.
GROUP_PAGE = {
    "AQ eReporting": "aq-ereporting",
    "Data flows monitors": "data-flows-monitors",
    "Data tables": "data-tables",
    "Air quality now": "air-quality-now",
    "Data analysis and stats": "data-analysis-and-stats",
    "Focus on cities": "focus-on-cities",
    "Compliance status": "compliance-status",
    "Impact on health": "impact-on-health",
}

GROUP_ORDER = list(GROUP_PAGE)


def card(app: dict, depth: str = "../") -> str:
    """One application as a linked thumbnail card."""
    thumb = THUMBS_DIR / f"{app['id']}.jpg"
    name = html.escape(app["name"])
    url = html.escape(app["url"], quote=True)

    if thumb.exists():
        media = (f'<img src="{depth}_static/thumbnails/{app["id"]}.jpg" '
                 f'alt="Screenshot of {name}" loading="lazy">')
    else:
        # 42 and 43 return 404 on the portal's own links; say so rather than
        # showing an empty frame.
        media = '<span class="app-card-missing">Not available</span>'

    badge = '<span class="app-card-badge">discontinued</span>' if app["discontinued"] else ""
    return (f'<a class="app-card" href="{url}">'
            f'<span class="app-card-shot">{media}</span>'
            f'<span class="app-card-title">{name}{badge}</span></a>')


def grid(apps: list[dict], depth: str = "../") -> str:
    cards = "\n".join(card(a, depth) for a in apps)
    return f'<div class="app-grid">\n{cards}\n</div>'


def write_viewers_index(apps: list[dict]) -> None:
    VIEWERS_INDEX.parent.mkdir(parents=True, exist_ok=True)
    missing = [a for a in apps if not (THUMBS_DIR / f"{a['id']}.jpg").exists()]

    out = [
        "# Viewers and dashboards", "",
        f"The {len(apps)} interactive viewers, dashboards and data tables that the "
        "European Air Quality Portal links to, grouped as the portal groups them. "
        "Each one opens in a new tab.", "",
        "```{note}",
        "These applications are hosted by the EEA on Tableau Public, discomap and "
        "related services — they are not part of this documentation. The thumbnails "
        "are screenshots taken when this page was generated, so the live "
        "application may look different.",
        "```", "",
    ]
    if missing:
        names = ", ".join(f"{m['name']} ({m['id']})" for m in missing)
        out += ["```{warning}",
                f"No thumbnail for {names} — the portal's link returns "
                "404 and the application appears to be gone.",
                "```", ""]

    for group in GROUP_ORDER:
        members = [a for a in apps if a["box"] == group]
        if not members:
            continue
        page = GROUP_PAGE[group]
        out += [f"## {group}", "",
                f"{len(members)} applications — see [{group}](../pages/{page}.md) "
                "for the portal's description.", "",
                grid(members), ""]

    VIEWERS_INDEX.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {VIEWERS_INDEX} ({len(apps)} applications)")


def inject_into_pages(apps: list[dict]) -> None:
    for group, slug in GROUP_PAGE.items():
        members = [a for a in apps if a["box"] == group]
        page = PAGES_DIR / f"{slug}.md"
        if not members or not page.exists():
            print(f"  skip {slug}: {'no page' if members else 'no applications'}")
            continue

        block = "\n".join([
            START,
            "",
            "## Viewers in this section", "",
            f"{len(members)} interactive applications. Each opens in a new tab; "
            "see [all viewers and dashboards](../viewers/index.md) for the full catalogue.",
            "",
            grid(members),
            "",
            END,
        ])

        text = page.read_text(encoding="utf-8")
        if START in text and END in text:
            head, _, rest = text.partition(START)
            _, _, tail = rest.partition(END)
            text = head + block + tail
        else:
            text = text.rstrip() + "\n\n" + block + "\n"
        page.write_text(text, encoding="utf-8")
        print(f"  {slug}: {len(members)} applications")


def main() -> int:
    if not CATALOGUE.exists():
        print(f"{CATALOGUE} missing — run scripts/capture_thumbnails.py first",
              file=sys.stderr)
        return 1
    apps = json.loads(CATALOGUE.read_text(encoding="utf-8"))
    have = sum(1 for a in apps if (THUMBS_DIR / f"{a['id']}.jpg").exists())
    print(f"Catalogue: {len(apps)} applications, {have} with thumbnails")
    write_viewers_index(apps)
    print("Injecting per-page galleries:")
    inject_into_pages(apps)
    return 0


if __name__ == "__main__":
    sys.exit(main())
